### ISSUE TITLE
Update country data pack to use ISO country lists

### ISSUE THREAD

**Issue by marcolarosa** [Arkisto-Platform/describo-data-packs#1]
* [ ] include geo information for each country (presumably boundaries).
    * [ ] model as 
```
see https://schema.org/Country
{
  @id: ''.
  @type: Country,
  name: '',
  geo: can be GeoCoordinates or GeoShape
}
```

**Comment by Supertyp** [comment]
used geoShape:

[
 {
  "@type": "Country",
  "@id": "https://www.ethnologue.com/country/AD",
  "name": "Andorra",
  "alternateName": "AD",
  "iso_3": "AND",
  "geoShape": {
   "type": "Polygon",
   "coordinates": [
    [
     [
      1.707006470000067,
      42.5027814740001
     ],
     [
      1.697498006000075,
      42.49446156900012
     ],
...
}}]

**Comment by marcolarosa** [comment]
@Supertyp 

Can you please make the geoShape property "geojson" and stringify it (as per the instructions for language @ https://github.com/Arkisto-Platform/describo-data-packs/issues/2#issuecomment-1119166403). I forgot to update this ticket! @ptsefton has added the geojson property to the ldaca ontology.

@ptsefton Can you please keep an eye out on these tickets. Looks like we need a property "iso_3" added to the ontology as well.

**Comment by Supertyp** [comment]
- I changed 'geoShape' to 'geojson'
- the geojson value is stringify'd
- switched position of id and type

new data file at: describo-data-packs/country-main-data-pack.json

[
	{
		"@id":"https://www.ethnologue.com/country/AD",
		"@type":"Country",
		"name":"Andorra",
		"alternateName":"AD",
		"iso_3":"AND",
		"geojson":"{\"type\":\"Polygon\",\"coordinates\":[[[1.707006470000067,42.5027814740001],
		[1.697498006000075,42.49446156900012],[1.68633589600006,42.49061167500008],[1.6742436110
		00065,42.49050832100005],[1.662358032000043,42.493712260000024],[1.659774210000137,42.49
		681284600007],[1.656983683000078,42.49763966900008],[1.653986450000048,42.4965286260001]
		,[1.650369100000063,42.49340220200014],[1.639517049000119,42.46642710400002],[1.60747...
		}
	}...
]

**Comment by Supertyp** [comment]
I just changed the geojson to include the full feature instead of just the geometry:

"geojson":"{\"type\":\"Feature\",\"properties\":{\"ADMIN\":\"Andorra\",\"ISO_A3\":\"AND\"},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[1.707006470000067,42.5027814740001],[1.697498006000075,42.49446156...

**Comment by ptsefton** [comment]
what;s iso_3? seems like a weird one, I get geojson

----------------------------

Dr Peter Sefton
Senior Technical Advisor, School of Languages and Culture
Mobile: 0404 096 932

________________________________

**Comment by Supertyp** [comment]
iso_3 is the ISO 3166-1 alpha-3 format. The geojson data came with a mapping to this format so I included it. I think we could remove it as it does not add more information to the two-letter format used in ethnologue. It is also already included in the properties of the geojson feature.
