### ISSUE TITLE
Update language data pack

### ISSUE THREAD

**Issue by marcolarosa** [Arkisto-Platform/describo-data-packs#2]
* [x] include glottolog languages, austland and iso-6393 languages

**Comment by marcolarosa** [comment]
Further to our chat just now. Talk to @nthieberger about this but do we include an entry for each language from each source (ie an entry for aaa from glottolog and an entry from @austlang). When creating the entries the @id prop must map back to the unique URL. And when creating the language blobs invent properties if you need to: e.g. code for language code, geo for the coordinate information (this follows the way it's been done by schema.org/Country).

**Comment by marcolarosa** [comment]
from conversation with @nthieberger 

- each source will have unique language codes so we don't have to worry about overlap. 
- nice to have: for each language blob to have a property which links this blob to the language in other sources 
  - e.g. noongar in austlang has a corresponding entry in glottlog and ISO 6393
- the geojson field should have a valid geojson feature stringified

```
   @id: glottolog id,
   @type: Language,
   languageCode: {glottolog code},
   name: {language name}
   geojson: {geography data},
   source: 'Glottolog | Austlang | ...',
   sameAs: [ 
      { @id: { austlang id1 }},
      { @id: { austlang id2 }},
      { @id: { austlang id3 }},
      { @id: { iso 6393 id1 }},
      { @id: { iso 6393 id2 }},
   ]
```


Example for noongar:
```
   @id: {glottolog url to noongar language},
   @type: Language,
   languageCode: nyun1247,
   name: {language name}
   geojson: {geography data},
   source: 'Glottolog',
   sameAs: [ 
      { @id: { URL to iso 6393/nys }},
      { @id: { URL to austlang/W41 }},
   ]
```

**Comment by Supertyp** [comment]
Out of the 1200 languages in Austlang, 273 can be matched to the glottolog languages by name. The way I understand Nick, those languages would have two entries. One with a austlang id and one with a glottolog id. And then they would be cross-referenced in the "sameAs" list. Is that how I should go about it?

**Comment by ptsefton** [comment]
sameAs makes sense to me

----------------------------

Dr Peter Sefton
Senior Technical Advisor, School of Languages and Culture
Mobile: 0404 096 932

________________________________

**Comment by nthieberger** [comment]
Yes, 'sameAs', but glottolog also has ISO-639-3 equivalents that should map
to Austlang so the three can be 'sameAS'

**Comment by Supertyp** [comment]
Here is an example of what the cross referenced entries look like now. In "sameAs" they both refer to ethnologue and to each other:

{
	"@id": "https://collection.aiatsis.gov.au/austlang/language/Y63.1",
	"@type": "Language",
	"languageCode": "Y63.1",
	"name": "Barrow Point",
	"geojson": "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[\"-14.475977159965\",\"144.59443977457\"]}}",
	"source": "Austlang",
	"sameAs": [
		{
			"@id": "https://glottolog.org/resource/languoid/id/barr1247"
		},
		{
			"@id": "https://www.ethnologue.com/language/bpt"
		}
	],
	"alternateName": "Barrow Point language, Mutumui, Itu, Walmbaria, Basthom, Basthon, Baulam, Ebole, Eibole, Eipolin, Jugaiwatha, Karbungga, Mbambylmu, Mutumi, Njegudi, Ongwara, Mudumui"
},
{
	"@id": "https://glottolog.org/resource/languoid/id/barr1247",
	"@type": "Language",
	"languageCode": "barr1247",
	"name": "Barrow Point",
	"geojson": "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[\"-14.1219\",\"144.531\"]}}",
	"source": "Glottolog",
	"sameAs": [
		{
			"@id": "https://www.ethnologue.com/language/bpt"
		},
		{
			"@id": "https://collection.aiatsis.gov.au/austlang/language/Y63.1"
		}
	],
	"alternateName": "Barrow point [sv], Mutumui, Barrow Point language, Basthom, Basthon, Baulam, Ebole, Eibole, Eipolin, Itu, Jugaiwatha, Karbungga, Mbambylmu, Mudumui, Mutumi, Njegudi, Ongwara, Walmbaria"
},

**Comment by ptsefton** [comment]
Looks good though you will have to escape the strings in the embedded geojson with \" -- maybe you did and it's been taken out by a copy and paste?

----------------------------

Dr Peter Sefton
Senior Technical Advisor, School of Languages and Culture
Mobile: 0404 096 932

________________________________

**Comment by Supertyp** [comment]
Oh. Yes. Here is what it looks like in the json file:

```
{
	"@id": "https://collection.aiatsis.gov.au/austlang/language/Y63.1",
	"@type": "Language",
	"languageCode": "Y63.1",
	"name": "Barrow Point",
	"geojson": "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[\"-14.475977159965\",\"144.59443977457\"]}}",
	"source": "Austlang",
	"sameAs": [
		{
			"@id": "https://glottolog.org/resource/languoid/id/barr1247"
		},
		{
			"@id": "https://www.ethnologue.com/language/bpt"
		}
	],
	"alternateName": "Barrow Point language, Mutumui, Itu, Walmbaria, Basthom, Basthon, Baulam, Ebole, Eibole, Eipolin, Jugaiwatha, Karbungga, Mbambylmu, Mutumi, Njegudi, Ongwara, Mudumui"
},
{
	"@id": "https://glottolog.org/resource/languoid/id/barr1247",
	"@type": "Language",
	"languageCode": "barr1247",
	"name": "Barrow Point",
	"geojson": "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[\"-14.1219\",\"144.531\"]}}",
	"source": "Glottolog",
	"sameAs": [
		{
			"@id": "https://www.ethnologue.com/language/bpt"
		},
		{
			"@id": "https://collection.aiatsis.gov.au/austlang/language/Y63.1"
		}
	],
	"alternateName": "Barrow point [sv], Mutumui, Barrow Point language, Basthom, Basthon, Baulam, Ebole, Eibole, Eipolin, Itu, Jugaiwatha, Karbungga, Mbambylmu, Mudumui, Mutumi, Njegudi, Ongwara, Walmbaria"
},
```

**Comment by ptsefton** [comment]
Ok great - so what's the plan in PARADISEC - to refer to both of these for each file or Object that contains language resources or just one?

----------------------------

Dr Peter Sefton
Senior Technical Advisor, School of Languages and Culture
Mobile: 0404 096 932

________________________________

**Comment by nthieberger** [comment]
The plan is to allow entry of all of these for any item, and to automate so
that choice of one that is linked to others will auto populate with others

**Comment by ptsefton** [comment]
For the metadata profile we need to recommend what a record should look like when shared (the workings of the app automation are not in scope) - so what you are saying @nthieberger implies that there should be redundant descriptions where there is a match with more than one of the vocabs for shared (and maybe archived) metadata records?

**Comment by marcolarosa** [comment]
@nthieberger Adding an entry for a language from each available source is unmanageable and doesn't add anything to the data description other than noise. Think of some of the Capell items with 50 odd languages listed against them. With 3 sources that becomes 150 entries. I don't think this is the correct way forward.

**Comment by nthieberger** [comment]
OK, so, instead, we let a user select from any of the three possible
standard forms, but how do we prevent them selecting three for any given
language? They need to select the one that gives best accuracy for the
language, in some cases only one of the three will apply so that will be
the choice. For searching we need to allow the related codes to be found
too, Searching for ISO 639-3 wbt will also search for Glottolog wanm1242
and Austlang A62.

**Comment by marcolarosa** [comment]
We can limit the set of choices available in some environments; e.g. for nyingarn we might only make the Austlang entries available for selection. 

But if all are available then we need to educate users so that they preferentially select one source over another if they get multiple matches in a given setting. If they choose to just add each of the 3 entries that's not as bad as the system automatically adding 3 entries for every language selection. But I can't stress enough that we need to educate people on how this modelling needs to be done.

**Comment by marcolarosa** [comment]
@Supertyp 

Can you please update the language entries so that the geojson property looks like:

```
{
	"@id": "https://collection.aiatsis.gov.au/austlang/language/Y63.1",
	"@type": "Language",
	"languageCode": "Y63.1",
	"name": "Barrow Point",
	"geojson": {
             @id: "#{name},
             @type: "GeoCoordinates",
             geojson: "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[\"-14.475977159965\",\"144.59443977457\"]}}",
	},
        "source": "Austlang",
	"sameAs": [
		{
			"@id": "https://glottolog.org/resource/languoid/id/barr1247"
		},
		{
			"@id": "https://www.ethnologue.com/language/bpt"
		}
	],
	"alternateName": "Barrow Point language, Mutumui, Itu, Walmbaria, Basthom, Basthon, Baulam, Ebole, Eibole, Eipolin, Jugaiwatha, Karbungga, Mbambylmu, Mutumi, Njegudi, Ongwara, Mudumui"
},

And likewise for the country data please.

**Comment by Supertyp** [comment]
done! the language entries look like this now:

```
    {
        "@id": "https://glottolog.org/resource/languoid/id/kolp1236",
        "@type": "Language",
        "languageCode": "kolp1236",
        "name": "Kol (Papua New Guinea)",
        "geojson": {
            "@id": "#Kol (Papua New Guinea)",
            "@type": "GeoCoordinates",
            "geojson": "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[\"-5.21042\",\"151.583\"]}}"
        },
        "source": "Glottolog",
        "sameAs": [
            {
                "@id": "https://www.ethnologue.com/language/kol"
            }
        ],
        "alternateName": ""
    },
```

For the country items, I used for type in geojson 'GeoShape' instead of 'GeoCoordinates'
