### ISSUE TITLE
Add code to support lookups

### ISSUE THREAD

**Issue by marcolarosa** [Arkisto-Platform/describo-data-packs#3]
* [x] be able to import a method from this library where the user can specify the data pack and what to search for

```
export function lookup({ packName, find, fields = ['@id', 'name', 'alternateName' ], filter = {} }) {
}
```

  * packName: name of the data pack: e.g. countries, languages, camera's etc
  * find: query string 
  * fields: array of fields to look in; default: @id, name  but can be specified by the caller at run time
  * filter: object to use as filter. e.g: filter = { source: 'glottolog' } perform the lookup only on languages that match source: 'glottolog'

To make this easier on the calling application we might want a top level index that maps a pointer from the `packName` to the actual data file online. e.g.

```
{
  Austlang: https://raw.githubusercontent.com/Arkisto-Platform/describo-data-packs/master/Austlang-language-data/austlang-language-data-pack.json,
  Glottolog: https://github.com/Arkisto-Platform/describo-data-packs/blob/3ad3c527899bff4d712c65c2563731ab50ffb691/Glottolog-language-data/glottolog-language-data-pack.json,
  Language: ['Austlang', 'Glottolog', ....' ],
}
```

Then, when the calling app calls `lookup({ packName: ['Austlang']...)` the code could download from github and cache locally for use next time.

Also have a look at https://github.com/Language-Research-Technology/language-data-node-tools/blob/master/lib/langs.js

**Comment by marcolarosa** [comment]
See https://github.com/Arkisto-Platform/describo-data-packs/issues/4 and https://github.com/Arkisto-Platform/describo-data-packs/issues/5

**Comment by Supertyp** [comment]
I got the lookup function in lookup.js which requires the datapacks array from index.js  
some examples for lookups can be found in lookup_test.js

I experimented with async-await but settled on using promises for fetching the files parallel if there are more than one.

The lookup as of now does not include the crossreferencing of Austlang and Glottolog ids yet.

**Comment by marcolarosa** [comment]
done for now
